### PR TITLE
Update NuGet.Config

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by clairernovotny** [comment]
not sure why you're deleting the private feed as we consume packages from there that aren't on nuget.org.

**Comment by Youssef1313** [comment]
@clairernovotny See [dependency confusion attack](https://aka.ms/pkg-sec-wp).
If some packages are not on nuget.org, you need to mirror them in the private feed to mitigate the attack.

**Comment by clairernovotny** [comment]
That's not possible with public feeds and Open Source projects can't use private feeds. This is not subject to that attack as the other feed is fully trusted.

**Comment by Youssef1313** [comment]
@clairernovotny If the private feed has packages that don't exist on nuget.org, an attacker could upload his own package with that name on nuget.org.

Could you check please if the build fails as a result of this change, and which package(s) cause it to fail?

**Pull request closed without merging**
